// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGzzXDRzQj7RbiZJQfvwZEpnO0vHzSMsk',
    appId: '1:124871515546:web:eb590616399dd2dc10792c',
    messagingSenderId: '124871515546',
    projectId: 'pagpagapp',
    authDomain: 'pagpagapp.firebaseapp.com',
    storageBucket: 'pagpagapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGzzXDRzQj7RbiZJQfvwZEpnO0vHzSMsk',
    appId: '1:124871515546:android:0f98d17e8a104e71b1ee23',
    messagingSenderId: '124871515546',
    projectId: 'pagpagapp',
    storageBucket: 'pagpagapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHv0W_SQdzTf9tctrSrogk6KkWhD-YUvU',
    appId: '1:124871515546:ios:022617e3375e9945b1ee23',
    messagingSenderId: '124871515546',
    projectId: 'pagpagapp',
    storageBucket: 'pagpagapp.firebasestorage.app',
    iosBundleId: 'com.pagpag.pagpagapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsFaxeejMMNYvjzZVdIXhv8dQJEI3Xq1Y',
    appId: '1:124871515546:ios:9da6a3d40a751e12b1ee23',
    messagingSenderId: '124871515546',
    projectId: 'pagpagapp',
    authDomain: 'pagpagapp.firebaseapp.com',
    storageBucket: 'pagpagapp.firebasestorage.app',
    iosBundleId: 'com.nevescapital.pagpag',
  );
}

// ✅ Configurações unificadas para o projeto: pagpagapp
// Todas as plataformas agora usam o mesmo projeto Firebase
