// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe07Wz57gux94qiv_BxMExGEhdpGnO_BA',
    appId: '1:1065108873797:web:eb590616399dd2dc10792c',
    messagingSenderId: '1065108873797',
    projectId: 'apppagpag',
    authDomain: 'apppagpag.firebaseapp.com',
    storageBucket: 'apppagpag.firebasestorage.app',
    measurementId: 'G-WRFMJ5262Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NyLDzCjntVz2QOe5SNhG7p9B75MUXrk',
    appId: '1:1065108873797:android:86824ad9c25563bb10792c',
    messagingSenderId: '1065108873797',
    projectId: 'apppagpag',
    storageBucket: 'apppagpag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2NyLDzCjntVz2QOe5SNhG7p9B75MUXrk',
    appId: '1:1065108873797:ios:a7f889b04f6a459c10792c',
    messagingSenderId: '1065108873797',
    projectId: 'apppagpag',
    authDomain: 'apppagpag.firebaseapp.com',
    storageBucket: 'apppagpag.firebasestorage.app',
    iosBundleId: 'com.example.nevesCapital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2NyLDzCjntVz2QOe5SNhG7p9B75MUXrk',
    appId: '1:1065108873797:ios:a7f889b04f6a459c10792c',
    messagingSenderId: '1065108873797',
    projectId: 'apppagpag',
    authDomain: 'apppagpag.firebaseapp.com',
    storageBucket: 'apppagpag.firebasestorage.app',
    iosBundleId: 'com.example.nevesCapital',
  );
}

// 📝 INSTRUÇÕES PARA CONFIGURAR:
// 1. Execute: flutterfire configure
// 2. Ou substitua manualmente os valores acima pelos seus dados reais
// 3. Os dados reais estão nos arquivos:
//    - android/app/google-services.json
//    - ios/Runner/GoogleService-Info.plist