# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    
    # Opção 1: Usar API Key do App Store Connect (RECOMENDADO)
    # Mais seguro e funciona melhor com versões recentes do Fastlane
    # Descomente e configure com suas informações:
    # upload_to_testflight(
    #   api_key_path: "./fastlane/AuthKey_XXXXXXXX.p8",
    #   api_key_issuer_id: "seu-issuer-id",
    #   api_key_key_id: "seu-key-id",
    #   skip_waiting_for_build_processing: true
    # )
    
    # Opção 2: Usar username + senha específica do app (via variável de ambiente)
    # Configure: export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="sua-senha"
    upload_to_testflight(
      username: "adm@neves.capital",
      skip_waiting_for_build_processing: true
    )
  end
end
